/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface BonusContract extends Truffle.Contract<BonusInstance> {
  "new"(
    _btcp: string,
    _treasury: string,
    _admin: string,
    meta?: Truffle.TransactionDetails
  ): Promise<BonusInstance>;
}

export interface BonusClaimed {
  name: "BonusClaimed";
  args: {
    user: string;
    nonce: BN;
    amount: BN;
    bonusType: BN;
    0: string;
    1: BN;
    2: BN;
    3: BN;
  };
}

export interface OwnershipTransferred {
  name: "OwnershipTransferred";
  args: {
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
  };
}

type AllEvents = BonusClaimed | OwnershipTransferred;

export interface BonusInstance extends Truffle.ContractInstance {
  admin(txDetails?: Truffle.TransactionDetails): Promise<string>;

  btcp(txDetails?: Truffle.TransactionDetails): Promise<string>;

  claimBonus: {
    (
      _nonce: number | BN | string,
      _amount: number | BN | string,
      _expiration: number | BN | string,
      _type: number | BN | string,
      _sig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _nonce: number | BN | string,
      _amount: number | BN | string,
      _expiration: number | BN | string,
      _type: number | BN | string,
      _sig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _nonce: number | BN | string,
      _amount: number | BN | string,
      _expiration: number | BN | string,
      _type: number | BN | string,
      _sig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _nonce: number | BN | string,
      _amount: number | BN | string,
      _expiration: number | BN | string,
      _type: number | BN | string,
      _sig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  claimed(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  renounceOwnership: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  transferOwnership: {
    (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  treasury(txDetails?: Truffle.TransactionDetails): Promise<string>;

  updateAdmin: {
    (_admin: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_admin: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _admin: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _admin: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateTreasury: {
    (_treasury: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _treasury: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _treasury: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _treasury: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    admin(txDetails?: Truffle.TransactionDetails): Promise<string>;

    btcp(txDetails?: Truffle.TransactionDetails): Promise<string>;

    claimBonus: {
      (
        _nonce: number | BN | string,
        _amount: number | BN | string,
        _expiration: number | BN | string,
        _type: number | BN | string,
        _sig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _nonce: number | BN | string,
        _amount: number | BN | string,
        _expiration: number | BN | string,
        _type: number | BN | string,
        _sig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _nonce: number | BN | string,
        _amount: number | BN | string,
        _expiration: number | BN | string,
        _type: number | BN | string,
        _sig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _nonce: number | BN | string,
        _amount: number | BN | string,
        _expiration: number | BN | string,
        _type: number | BN | string,
        _sig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    claimed(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    renounceOwnership: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    transferOwnership: {
      (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    treasury(txDetails?: Truffle.TransactionDetails): Promise<string>;

    updateAdmin: {
      (_admin: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _admin: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _admin: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _admin: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateTreasury: {
      (_treasury: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _treasury: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _treasury: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _treasury: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
