/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableUpgradeableContract } from "./OwnableUpgradeable";
import { ERC1155UpgradeableContract } from "./ERC1155Upgradeable";
import { IERC1155MetadataURIUpgradeableContract } from "./IERC1155MetadataURIUpgradeable";
import { IERC1155ReceiverUpgradeableContract } from "./IERC1155ReceiverUpgradeable";
import { IERC1155UpgradeableContract } from "./IERC1155Upgradeable";
import { ERC165UpgradeableContract } from "./ERC165Upgradeable";
import { IERC165UpgradeableContract } from "./IERC165Upgradeable";
import { OwnableContract } from "./Ownable";
import { IERC1155Contract } from "./IERC1155";
import { ERC20Contract } from "./ERC20";
import { ERC20CappedContract } from "./ERC20Capped";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC20Contract } from "./IERC20";
import { ERC721Contract } from "./ERC721";
import { ERC721EnumerableContract } from "./ERC721Enumerable";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { ERC165Contract } from "./ERC165";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { BattleContract } from "./Battle";
import { ProphetV2Contract } from "./ProphetV2";
import { ProphetV2StorageContract } from "./ProphetV2Storage";
import { OrbContract } from "./Orb";
import { ShopContract } from "./Shop";
import { PoolInitializableContract } from "./PoolInitializable";
import { PoolFactoryContract } from "./PoolFactory";
import { TCPContract } from "./TCP";
import { TokenVestingContract } from "./TokenVesting";
import { VestingDetailsContract } from "./VestingDetails";
import { VestingStorageContract } from "./VestingStorage";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "OwnableUpgradeable"): OwnableUpgradeableContract;
      require(name: "ERC1155Upgradeable"): ERC1155UpgradeableContract;
      require(
        name: "IERC1155MetadataURIUpgradeable"
      ): IERC1155MetadataURIUpgradeableContract;
      require(
        name: "IERC1155ReceiverUpgradeable"
      ): IERC1155ReceiverUpgradeableContract;
      require(name: "IERC1155Upgradeable"): IERC1155UpgradeableContract;
      require(name: "ERC165Upgradeable"): ERC165UpgradeableContract;
      require(name: "IERC165Upgradeable"): IERC165UpgradeableContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "IERC1155"): IERC1155Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC20Capped"): ERC20CappedContract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721Enumerable"): ERC721EnumerableContract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "Battle"): BattleContract;
      require(name: "ProphetV2"): ProphetV2Contract;
      require(name: "ProphetV2Storage"): ProphetV2StorageContract;
      require(name: "Orb"): OrbContract;
      require(name: "Shop"): ShopContract;
      require(name: "PoolInitializable"): PoolInitializableContract;
      require(name: "PoolFactory"): PoolFactoryContract;
      require(name: "TCP"): TCPContract;
      require(name: "TokenVesting"): TokenVestingContract;
      require(name: "VestingDetails"): VestingDetailsContract;
      require(name: "VestingStorage"): VestingStorageContract;
    }
  }
}

export {
  OwnableUpgradeableContract,
  OwnableUpgradeableInstance,
} from "./OwnableUpgradeable";
export {
  ERC1155UpgradeableContract,
  ERC1155UpgradeableInstance,
} from "./ERC1155Upgradeable";
export {
  IERC1155MetadataURIUpgradeableContract,
  IERC1155MetadataURIUpgradeableInstance,
} from "./IERC1155MetadataURIUpgradeable";
export {
  IERC1155ReceiverUpgradeableContract,
  IERC1155ReceiverUpgradeableInstance,
} from "./IERC1155ReceiverUpgradeable";
export {
  IERC1155UpgradeableContract,
  IERC1155UpgradeableInstance,
} from "./IERC1155Upgradeable";
export {
  ERC165UpgradeableContract,
  ERC165UpgradeableInstance,
} from "./ERC165Upgradeable";
export {
  IERC165UpgradeableContract,
  IERC165UpgradeableInstance,
} from "./IERC165Upgradeable";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { IERC1155Contract, IERC1155Instance } from "./IERC1155";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC20CappedContract, ERC20CappedInstance } from "./ERC20Capped";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721EnumerableContract,
  ERC721EnumerableInstance,
} from "./ERC721Enumerable";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { BattleContract, BattleInstance } from "./Battle";
export { ProphetV2Contract, ProphetV2Instance } from "./ProphetV2";
export {
  ProphetV2StorageContract,
  ProphetV2StorageInstance,
} from "./ProphetV2Storage";
export { OrbContract, OrbInstance } from "./Orb";
export { ShopContract, ShopInstance } from "./Shop";
export {
  PoolInitializableContract,
  PoolInitializableInstance,
} from "./PoolInitializable";
export { PoolFactoryContract, PoolFactoryInstance } from "./PoolFactory";
export { TCPContract, TCPInstance } from "./TCP";
export { TokenVestingContract, TokenVestingInstance } from "./TokenVesting";
export {
  VestingDetailsContract,
  VestingDetailsInstance,
} from "./VestingDetails";
export {
  VestingStorageContract,
  VestingStorageInstance,
} from "./VestingStorage";
