/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface VRFCoordinatorMockContract
  extends Truffle.Contract<VRFCoordinatorMockInstance> {
  "new"(
    linkAddress: string,
    meta?: Truffle.TransactionDetails
  ): Promise<VRFCoordinatorMockInstance>;
}

export interface RandomnessRequest {
  name: "RandomnessRequest";
  args: {
    sender: string;
    keyHash: string;
    seed: BN;
    0: string;
    1: string;
    2: BN;
  };
}

type AllEvents = RandomnessRequest;

export interface VRFCoordinatorMockInstance extends Truffle.ContractInstance {
  LINK(txDetails?: Truffle.TransactionDetails): Promise<string>;

  callBackWithRandomness: {
    (
      requestId: string,
      randomness: number | BN | string,
      consumerContract: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      requestId: string,
      randomness: number | BN | string,
      consumerContract: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      requestId: string,
      randomness: number | BN | string,
      consumerContract: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      requestId: string,
      randomness: number | BN | string,
      consumerContract: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  onTokenTransfer: {
    (
      sender: string,
      fee: number | BN | string,
      _data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      sender: string,
      fee: number | BN | string,
      _data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      sender: string,
      fee: number | BN | string,
      _data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sender: string,
      fee: number | BN | string,
      _data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    LINK(txDetails?: Truffle.TransactionDetails): Promise<string>;

    callBackWithRandomness: {
      (
        requestId: string,
        randomness: number | BN | string,
        consumerContract: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        requestId: string,
        randomness: number | BN | string,
        consumerContract: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        requestId: string,
        randomness: number | BN | string,
        consumerContract: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        requestId: string,
        randomness: number | BN | string,
        consumerContract: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    onTokenTransfer: {
      (
        sender: string,
        fee: number | BN | string,
        _data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        sender: string,
        fee: number | BN | string,
        _data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        sender: string,
        fee: number | BN | string,
        _data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        sender: string,
        fee: number | BN | string,
        _data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
